### ISSUE TITLE
LZ batch analysis fails with GRPException 

### ISSUE THREAD

**Issue by ashinpan** [pnprog/goreviewpartner#101]
I am using the latest trunk version of GRP. The following is the terminal output:

==============
move 1
leela Zero play black
Adding new popup
Totally 3 popups
Removing popup
Totally 2 popups left
Number of alternative sequences: 12
==== no more sequences =====
==== creating heat map =====
converting GRPException error message from unicode to str
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pan/devel-goreview/toolbox.py", line 1067, in run_all_analysis
    answer=self.run_analysis(self.current_move)
  File "/home/pan/devel-goreview/leela_zero_analysis.py", line 135, in run_analysis
    raw_heat_map=leela_zero.get_heatmap()
  File "/home/pan/devel-goreview/leela_zero_analysis.py", line 223, in get_heatmap
    i,j=gtp2ij(coordinates)
  File "/home/pan/devel-goreview/toolbox.py", line 123, in gtp2ij
    raise GRPException("Cannot convert GTP coordinates "+str(move)+" to grid coordinates!")
GRPException: Cannot convert GTP coordinates a1 to grid coordinates!

**Comment by pnprog** [comment]
Hi!
Thanks for reporting the bug. I had introduced that bug a few days ago for both Leela.
It is fixed now.

**Comment by ashinpan** [comment]
@pnprog Thanks for fixing the bug. It is working now. I will close the issue.

**Comment by pnprog** [comment]
Yep, sorry about that: I am somehow on vacation, so I have time to work on GRP, but I don't have my usual computer with me (with all the bots installed and working) so it's hard to test properly for the changes I make.

**Comment by ashinpan** [comment]
@pnprog  It is OK. We users must still appreciate what you have done for us.
