### ISSUE TITLE
GoReviewPartner throws exception with PhoenixGo 

### ISSUE THREAD

**Issue by verheij** [pnprog/goreviewpartner#122]
After changing the folder manually PhoenixGo starts, but GRP throws an exception. I started the analysis at move 17; Windows 10, 64-bit. sgf-file attached (I had to change the extension)
[test.txt](https://github.com/pnprog/goreviewpartner/files/2980620/test.txt)

winrate for first variation => 44.79%
winrate for first variation => 44.79%
Exception in thread Thread-30:
Traceback (most recent call last):
  File "threading.pyc", line 810, in __bootstrap_inner
  File "threading.pyc", line 763, in run
  File "toolbox.pyc", line 1047, in run_all_analysis
  File "phoenixgo_analysis.pyc", line 79, in run_analysis
  File "phoenixgo_analysis.pyc", line 272, in undo
  File "gtp.pyc", line 140, in undo
AttributeError: PhoenixGo_gtp instance has no attribute 'komi_value'

**Comment by pnprog** [comment]
Thanks for reporting the issue, I will look into it :)
