### ISSUE TITLE
error converting (some) rsgf files to csv

### ISSUE THREAD

**Issue by anova0515** [pnprog/goreviewpartner#124]
Hi,
I occasionally encounter the error below when using r2csv.py.

Traceback (most recent call last):
  File "/home/anova0515/goreviewpartner/r2csv.py", line 210, in <module>
    rsgf2csv(filename)
  File "/home/anova0515/goreviewpartner/r2csv.py", line 171, in rsgf2csv
    if table[1+m][c]=="":
IndexError: list index out of range

I attached two such problematic .rsgf files (had to change the extension to .txt for it to be accepted).

Note: I have successfully converted tens of thousands of rsgf files, so this is a somewhat rare occurrence.

[2000-05-08f.txt](https://github.com/pnprog/goreviewpartner/files/3071253/2000-05-08f.txt)
[1983-12-08c.txt](https://github.com/pnprog/goreviewpartner/files/3071254/1983-12-08c.txt)

**Comment by pnprog** [comment]
Thanks for reporting the issue, and providing the RSGF file, I will look into it.

> I have successfully converted tens of thousands of rsgf files

Oh wow! I did not know this feature could be **that** useful !
