### ISSUE TITLE
Error when asking Leela to play a move that is "resign"

### ISSUE THREAD

**Issue by BorisNA** [pnprog/goreviewpartner#25]
If I ask Leela to play a move when she'd like to resign, error appears. Something with incorrect objects/unassigned methods?

Leela is the latest 0.11 OpenCL, goreviewpartner is current from "master".

```
opening move 40
Asking Leela (Fast profile) to play one move
Leela play
move= resign in 3.0110001564 s
Exception in thread Thread-2:
Traceback (most recent call last):
  File "python-2.7.13.amd64\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "python-2.7.13.amd64\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "goreviewpartner-master\dual_view.py", line 564, in click_button
    bot.undo_resign()
AttributeError: LeelaOpenMove instance has no attribute 'undo_resign'
```

**Comment by pnprog** [comment]
Thanks for reporting the bug, I just fixed it.

**Comment by BorisNA** [comment]
Thank you! That was quick :)
