### ISSUE TITLE
r2sgf: Unicode Error

### ISSUE THREAD

**Issue by cooperstevenson** [pnprog/goreviewpartner#34]
Receive the following when converting an RSGF to SGF:

UnicodeEncodeError: 'latin-1' codec can't encode character u'\u2022' in position 260: ordinal not in range(256)

Locale settings:
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

config.ini 'language' setting set to 'en'

**Comment by cooperstevenson** [comment]
Of course, one can review the RSGF in an SGF editor by simply renaming the RSGF with an SGF extension.

**Comment by pnprog** [comment]
Hi!

Thanks for reporting the bug!

Could you share the complete error log, the one that includes file and line number?
If possible, the RSGF file as well.

**Comment by cooperstevenson** [comment]
My pleasure, here you go:

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Convertion of /tmp/foo.rsgf into /tmp/foo.rsgf.sgf
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "./main.py", line 74, in r2sgf
    rsgf2sgf(filename)
  File "/home/cstevens/src/go/goreviewpartner/r2sgf.py", line 16, in rsgf2sgf
    get_node(gameroot,current_move).set("C",comments)
  File "/home/cstevens/src/go/goreviewpartner/gomill/sgf.py", line 194, in set
    identifier, self._presenter.serialise(identifier, value))
  File "/home/cstevens/src/go/goreviewpartner/gomill/sgf_properties.py", line 730, in serialise
    self._get_effective_property_type(identifier), value)
  File "/home/cstevens/src/go/goreviewpartner/gomill/sgf_properties.py", line 695, in serialise_as_type
    serialised = property_type.serialiser(value, self)
  File "/home/cstevens/src/go/goreviewpartner/gomill/sgf_properties.py", line 264, in serialise_text
    s = s.decode("utf-8").encode(context.encoding)
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u2022' in position 260: ordinal not in range(256)


[rsgf.zip](https://github.com/pnprog/goreviewpartner/files/1867209/rsgf.zip)

**Comment by cooperstevenson** [comment]
If it's helpful I turned off the 'save bot command line into RSGF file' thinking that characters in the file name may cause an issue. I'm saddened to report that I received the same error with the feature disabled.

**Comment by pnprog** [comment]
I am out of  town this week, so I will check this when I came back.

**Comment by farnaby** [comment]
I encountered the same error and did a little research with pdb. The crash is caused by the sgf comment generated by leela-zero analysis. These comments use some sort of special unicode bullet point. When converting to sgf, it tries to convert the encoding to 'latin-1' by default, but the bullet symbol doesn't exist in this encoding. I worked around by patching line 264 in sgf_properties.py like this:

` s = s.decode("utf-8").encode(context.encoding, errors='replace')`

This means that encode won't raise an exception when it cannot encode a character. Instead, it just replaces it by some other symbol.

**Comment by pnprog** [comment]
I checked a bit, the bullet symbol is the one I used to describe the win rate changes in the left side comment box, like:

```
Move 10
White to play, in the game, white played Q7
For this position, Leela would play: Q7

White win probability:
 • before q7: 50.33%
 • after q7: 50.44% (+0.11pp)

White Value Network win probability:
 • before q7: 49.17%
 • after q7: 49.21% (+0.04pp)

White Monte Carlo win probability:
 • before q7: 52.51%
 • after q7: 52.74% (+0.23pp)
```

Those bullets are unicode characters. I cannot reproduce this error on my Ubuntu, only on Windows.

Thanks for the bug fix.

**Comment by pnprog** [comment]
I have investigating this issue a bit more, and the issue arrises when the original SGF does not contain the **CA** SGF property. This property indicates the encoding used inside the SGF file. Most of my SGF files contain **CA[UTF-8]**, and so do their respective RSGF files, so at the time of the conversion back to SGF, **gomill** would successfully encode that bullet character in UTF.
Now, if the SGF file does not contain that **CA** property, **gomill** tries to encode the SGF file in **ISO-8859-1** (I guess this is that **latin-1** encoding mentionned in the error log).

+ So I could try to enforce the encoding to **UTF-8** (I means, in 2018, who still does not use unicode?) but there are a lot of old kifus and go softwares around there, and they could contain non unicode characteres, so those characters would make the conversion to unicode fails.
+ I could just remove that bullet characters, and then, the remaining charateres should not create issues (there are **ascii** encoding, and other fancy encoding, like player names, would be in the same encoding of the original SGF file.)
+ Or some more elaborated solution, like:
    + if no declared encoding (or the declared encoding is **UTF-8**), try to enforce **UTF-8** encoding, and if fails, remove/replace that bullet character
    + if there is already a declared encoding, different than unicode, then remove/replace that bullet character

**Comment by pnprog** [comment]
I just went ahead an implemented the above mentioned "elaborated solution", which will try to enforce the SGF format in UTF-8 format : 79dfd45f11308274f096228e3e4055c91a3747f9

I am looking for old kifu with exotic encoding to try if it's working fine.
