### ISSUE TITLE
Analysis scripts need Display to run

### ISSUE THREAD

**Issue by peko19** [pnprog/goreviewpartner#38]
I would like to run a leela_zero analysis script on a cloud server without Xfree.
but it stops:

Traceback (most recent call last):
  File "leela_zero_analysis.py", line 454, in <module>
    app = Application()
  File "/home/peko/goreviewpartner/toolbox.py", line 1827, in __init__
    Tk.__init__(self)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

is there any quick fix to run it in a headless env?

**Comment by pnprog** [comment]
Hi!

Are you using the **--no-gui** command line parameter?

**Comment by peko19** [comment]
Hi,

sorry, didn't. it is just ok. thank you.
