### ISSUE TITLE
Reading SGF: KeyError

### ISSUE THREAD

**Issue by lebigot** [pnprog/goreviewpartner#58]
Opening a game fails every time, for all my SGF files (even those created by the creator of the SGF format!):
```
========= variation        
0                                                                               keeping only variation 0
size of the tree: 19                                                         
Setting new komi                                                  
Bot starting procedure started with profile = slow
        bot name: LeelaZero
        bot gtp name Leela Zero                   
Starting LeelaZero...               
Leela Zero working directory: /Users/lebigot/Downloads/leela-zero-master/src/
Checking Leela Zero stderr to check for OpenCL SGEMM tuner running
Could not find out, abandoning                                               
LeelaZero started                                                 
LeelaZero identification through GTP...                     
LeelaZero identified itself properly    
Checking version through GTP...        
Version: 0.15                       
Setting goban size as 19x19       
Clearing the board   
Checking for existing stones or handicap stones on the board                    
The SGF does not indicate handicap stone
The SGF indicates 0 occupied point(s)                       
Setting komi at 0.0                     
LeelaZero initialization completed   
Setting time per move
Saving RSGF file /Users/lebigot/Refs/Tnzrf/Go/Go_Seigen_games_commented/takagawa
.rsgf                
Stop_At_First_Resign is OFF                                                     Adding new popup
Totally 3 popups           
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/Users/lebigot/anaconda/envs/py2/lib/python2.7/threading.py", line 801,
in __bootstrap_inner                                                           
    self.run()      
  File "/Users/lebigot/anaconda/envs/py2/lib/python2.7/threading.py", line 754,
in run                                                                         
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/lebigot/Downloads/goreviewpartner-master/toolbox.py", line 916, i
n run_all_analysis                                                              
    answer=self.run_analysis(self.current_move)
  File "/Users/lebigot/Downloads/goreviewpartner-master/leela_zero_analysis.py",
 line 23, in run_analysis                                                       
    player_color=guess_color_to_play(self.move_zero,current_move)
  File "/Users/lebigot/Downloads/goreviewpartner-master/toolbox.py", line 638, i
n guess_color_to_play                                                           
    previous_move_color=guess_color_to_play(move_zero,move_number-1)
  File "/Users/lebigot/Downloads/goreviewpartner-master/toolbox.py", line 633, in guess_color_to_play
    if move_zero.get("PL").lower()=="b":       
  File "/Users/lebigot/Downloads/goreviewpartner-master/gomill/sgf.py", line 178, in get                 
    identifier, self._property_map[identifier])
KeyError: 'PL'               
```

Configuration: macOS 10.13.4, Python 2.7.14 (anaconda), GoReviewPartner revision e77c855.

**Comment by pnprog** [comment]
Hi @lebigot ,
I made several changes regarding opening of SGF files, could you have a try again and let me know?
