### ISSUE TITLE
goreviewpartner on MacOS

### ISSUE THREAD

**Issue by ranamar16** [pnprog/goreviewpartner#88]
I'm trying to run goReviewPartner, the program is going up, but when i test leela zero i get a pop up "[Errno 13] Permission denied", how do i solve it?

(with lizzie i get same response and i have in the terminal of lizzie this -
java.io.IOException: Cannot run program "./leelaz" (in directory "."): error=13, Permission denied
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
at featurecat.lizzie.analysis.Leelaz.(Leelaz.java:96)
at featurecat.lizzie.Lizzie.lambda$main$0(Lizzie.java:38)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=13, Permission denied
at java.lang.UNIXProcess.forkAndExec(Native Method)
at java.lang.UNIXProcess.(UNIXProcess.java:247)
at java.lang.ProcessImpl.start(ProcessImpl.java:134)
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
... 3 more)

**Comment by pnprog** [comment]
Hi!

I don't know much about MacOS, but I guess your **leelaz** executable does not have "execution rights".

On Unix systems like MacOs or Linux, the **chmod** command can be used: you have to open a terminal, position yourself in the folder that contain your **leelaz** executable then run the command `chmod +x leelaz`

Of course; there exist some way to do it without using the terminal, maybe this link can help: http://www.macinstruct.com/node/415

This should solve the issue with lizzie as  well.

**Comment by bjordan2010** [comment]
I am running Leela Zero on a Mac with GoReviewPartner and I do not get the permissions error.  Likely this has to do with the location of the Leela Zero engine files.   Likely the location of ./leelaz is in a system directory.  OP, try moving Leela Zero somewhere under ~/Documents/ and setting the config.ini appropriately.
