### ISSUE TITLE
Non english file name cause error on leela_analysis.py

### ISSUE THREAD

**Issue by mikita-herasiutsin** [pnprog/goreviewpartner#93]
If you try to analyze sgf files through leela_analysis.py with non english file name It will cause error. This happens at least on macOS

error:

python leela_zero_analysis.py --profile=Slow ~/Google\ Drive/GO/Партии\ с\ турниров\ Беларуси/*.sgf
GRP path: /Users/Mikita/workspace/goreviewpartner
Config file: /Users/Mikita/workspace/goreviewpartner/config.ini
Checking availability of config file
Reading language setting from config file
lang=en
Could not import the WX GUI library, please double check it is installed:
Avoiding wx
=> No problem, falling back to tkFileDialog
Variation: 1
Moves for this variation: 133
Range: all
Color: both
Komi: 6.5
Profile: Slow
Traceback (most recent call last):
  File "leela_zero_analysis.py", line 394, in <module>
    main(LeelaZero)
  File "/Users/Mikita/workspace/goreviewpartner/toolbox.py", line 2466, in main
    filename2=".".join(filename.split(".")[:-1])+".rsgf"
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 30: ordinal not in range(128)

**Comment by mikita-herasiutsin** [comment]
Created a PR to fix that https://github.com/pnprog/goreviewpartner/pull/94
